Jeol parsing, fixes #39
FAIRmat-NFDI/pynxtools-em pull request #43
Opened 2024-08-07 16:50 UTC by mkuehbach

2024-08-22 12:02 UTC, lukaspie requested changes
Mostly missing docstrings. Consider not using `print()`, but `logger.info()`

2024-08-22 12:02 UTC, lukaspie commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def parse(self, template: dict) -> dict:
docstring missing

2024-08-22 12:02 UTC, lukaspie commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def add_various_dynamic(self, template: dict) -> dict:
docstring missing

2024-08-22 12:02 UTC, lukaspie commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def add_various_static(self, template: dict) -> dict:
docstring missing

2024-08-22 12:41 UTC, lukaspie commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +        else:
logger.warning?

2024-08-26 10:28 UTC, mkuehbach commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +            print(
#62

2024-08-26 10:31 UTC, mkuehbach commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def add_various_dynamic(self, template: dict) -> dict:
Fixed

2024-08-26 10:31 UTC, mkuehbach commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +        else:
#62

2024-08-26 10:31 UTC, mkuehbach commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def add_various_static(self, template: dict) -> dict:
Fixed

2024-08-26 10:31 UTC, mkuehbach commented on src/pynxtools_em/parsers/image_tiff_jeol.py
> +    def parse(self, template: dict) -> dict:
Added

2024-08-26 12:15 UTC, merged